version: '3'
services:
  postgresql:
    restart: always
    image: mental/postgresql:9.6-2
    ports:
      - "5432:5432"
    environment:
      - DEBUG=false
      - PG_PASSWORD=

      - DB_USER=
      - DB_PASS=
      - DB_NAME=
    volumes:
      - postgre-data:/var/lib/postgresql
volumes:
  postgre-data: